### ISSUE TITLE
A* Optimization

### ISSUE THREAD

**Issue by broniec** [GTAirportNavigation/navigation-server#3]
BFS is currently implemented as an approach to find paths. However, I think in our case there are certain situations where we can implement heuristics to find locations faster. Example: Low Gate Numbers are always to the South. An easy way to prioritize something like this could be to insert into the open list at the front rather than the back.

**Comment by jiashenC** [comment]
I am thinking to have routing table for each node, because our map is static. We can precompute all reachable paths and then find the quickest path in the real time.
